### ISSUE TITLE
I can't clone homography_imitation_learning! 

### ISSUE THREAD

**Issue by hexiangdong2017** [RViMLab/h_rcm_vs_ws#1]
I followed the readme, and run 'git clone --recursive https://github.com/RViMLab/h_rcm_vs_ws'. But when cloning homography_imitation_learning, it require me to input the github username and password. I input my own github account and find I can't clone https://github.com/RViMLab/homography_imitation_learning.git. So, what's it?

**Comment by hexiangdong2017** [comment]
@mhubii

**Comment by mhubii** [comment]
hi @hexiangdong2017, https://github.com/RViMLab/homography_imitation_learning.git is a privat repository at the moment, and it can't be cloned. This is ongoing work and I don't want to open source it just yet. It will be open sourced in the future, but not for now. Sorry.

**Comment by mhubii** [comment]
this repository is now public
